TelegramConfig    :
  BotName                 : 'Quang_bot'
  # BotToken              : '5765659274:AAF1MrBZwC52uunp-t2CE6KhQn2yEmvKaik'
  # DeviceControlGroupID    : -1001625126544
  BotToken        : '6697911499:AAEtb1YHaM-pPgyJi3cSDQFEIrhL87n9Nfs'
  DeviceControlGroupID    : -4059748462

MqttConfig        :
  # Broker          : 'ptitteam:1883'
  Broker          : 'localhost:1883'
  User            : 'nmtam'
  Password        : '221220'
  TeleSrcTopic    : 'Telegram/GroupID/Rx'
  TeleDstTopic    : 'Telegram/+/Tx'

